services:
  app:
    build:
      context: .
      args:
        VITE_GOOGLE_CLIENT_ID: ${VITE_GOOGLE_CLIENT_ID}
        VITE_LRS_URL: ${VITE_LRS_URL}
        VITE_LRS_USERNAME: ${VITE_LRS_USERNAME}
        VITE_LRS_SECRET: ${VITE_LRS_SECRET}
        VITE_XAPI_ACTIVITY_BASE: ${VITE_XAPI_ACTIVITY_BASE}
    container_name: usccf-planning-tool
    ports:
      - "8080:80"
